### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by sauzny** [patorjk/photography-portfolio-template-1#1]
At first，I think you are a very good coder about javascript!!!
I want to learn javascript, vue or react.
which one is better?
can you give me some idea???
Thank you so much!

My En is not good, if I have some bad words,please forget it.Thank you!

==============================================
我是个中国程序员，我是写java的，我现在想学点js。
以前我看过你的博客和github。我觉得你写js很厉害！
我想问问你对vue和react的看法，你觉得哪个更好？

我的英语不太好，我把我的想法用中文再写一次，你要是不认识可以粘贴到谷歌翻译里看看。哈哈！

**Comment by patorjk** [comment]
You can't go wrong learning either, both are excellent. This project uses ReactJS. The biggest pluses for React are that there is a bigger ecosystem for it and it can be used for native apps too. Vue's advantages are that it is slightly simpler to learn. Learning either requires knowing JavaScript.
